let btntroca= document.querySelector("#btntroca")
let cardsig= document.querySelector("#cardsig")
let btnentrar= document.querySelector("#btnentrar")
let before= document.querySelector("#before")
let cardlog= document.querySelector("#cardlog")
let btntrocavolta= document.querySelector("#btntrocavolta")
let logobtn= document.querySelector("#logobtn")
let nav= document.querySelector("#l-nav")
let lheader= document.querySelector("#l-header")
let name= document.querySelector("#email")
let password= document.querySelector("#password")
let passwordrepeat = document.querySelector("#passwordrepeat")
var re = /\S+@\S+\.\S+/;
let A = /[A-Z]/;
let a = /[a-z]/;
let number = /[0-9]/;
let charx= /[!|@|#|$|%|^|&|*|(|)|-|_]/;
let button = document.querySelector("#button")
let user = document.querySelector("#user");
let labeluser = document.querySelector("#labeluser");
let logocenter = document.querySelector("#logocenter")